SET IDENTITY_INSERT [dbo].[MyLessons] ON
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (2, 1, N'start', N'Monday    ', N'02 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (3, 1, N'middle', N'Tuesday   ', N'02 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (4, 2, N'end', N'Monday    ', N'04 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (5, 2, N'debut', N'Tuesday   ', N'04 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (6, 2, N'middlegame', N'Wednesday ', N'04 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (7, 2, N'endgame', N'Friday    ', N'04 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (8, 3, N'1', N'Sunday', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (9, 3, N'2', N'Monday    ', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (10, 3, N'3', N'Tuesday   ', N'06 PM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (11, 4, N'1', N'Monday    ', N'08 PM    ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (12, 4, N'2', N'Wednesday ', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (13, 4, N'3', N'Sunday', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (14, 5, N'1', N'Monday    ', N'12 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (15, 5, N'2', N'Monday    ', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (16, 5, N'3', N'Tuesday', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (17, 6, N'1', N'Thursday', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (18, 6, N'2', N'Monday    ', N'10 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (19, 6, N'3', N'Sunday', N'08 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (20, 7, N'1', N'Sunday', N'06 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (21, 7, N'2', N'Monday    ', N'06 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (22, 7, N'3', N'Tuesday', N'06 AM     ')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (24, 8, N'1', N'Friday', N'02 PM')
INSERT INTO [dbo].[MyLessons] ([Id], [CourseId], [Title], [Day], [Time]) VALUES (25, 8, N'2', N'Friday', N'04 PM')
SET IDENTITY_INSERT [dbo].[MyLessons] OFF
